version: '3'
 
services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "./cmd/migration/main.go"]
    tty:
      true
    volumes:
      - .:/go/src/app
    depends_on:
      - postgres
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m
  slack_cmd:
    build:
      context: .
      dockerfile: Dockerfile
    tty:
      true
    volumes:
      - .:/go/src/app
    depends_on:
      - postgres
      - migrate
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      PGPASSWORD: password123
      POSTGRES_MULTIPLE_DATABASES: slack,slack_test
      TZ: "Asia/Tokyo"
    ports:
      - 0.0.0.0:54321:5432
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
volumes:
  postgres:
